version: "3.9"

services:
  api-service:
    build: "./API"
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - login-network
    env_file:
      - ./Docker/api.env

  frontend:
    build: "./frontend"
    ports:
      - "5173:80"
    depends_on:
      - api-service
    networks:
      - login-network

  postgres:
    image: postgres:14
    container_name: artisans-postgres
    ports:
      - "5432:5432"
    env_file:
      - ./Docker/db.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - login-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d artisans_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  login-network:
    driver: bridge

volumes:
  pgdata:
